id: DE111D660
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:58:13+00:00'
last_modified: '2022-05-27T16:04:53.592506+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d39d:
      image_group_id: I1PD95910
      title: ག་ཡ་མགོའི་རིའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: d39d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
