id: P105382A0
initial_creation_type: ocr
source_metadata:
  volumes:
    acad5e6046df411fa679f9adac5f61f4:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ག་ཡ་མགོའི་རིའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
